Repository rechen-werk/Kilian, pull requests merged in 2023-03, with the labels that each got.

#18 Early fix implementation.
  database.py
  kilian.py
Labels: bug, help wanted

#21 add /help
  kilian.py
Labels: documentation, enhancement, question

#22 Bugfixes
  README.md
  kilian.py
  requirements.txt
Labels: bug

#25 fix error for too long channel names
  kilian.py
Labels: bug

#27 Allow Dad IDs to be numeric
  kilian.py
Labels: enhancement

#29 Add op and deop command
  kilian.py
Labels: enhancement

#32 Feature archive
  database.py
  kilian.py
  sql_queries.py
Labels: enhancement
